# Generated by Django 5.2.7 on 2025-11-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="borrowed_books",
                to="libraryapp.libraryuser",
            ),
        ),
        migrations.AlterField(
            model_name="libraryuser",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
