# Generated by Django 5.2.7 on 2025-11-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0002_book_available_book_borrower_alter_libraryuser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="libraryuser",
            name="email",
        ),
        migrations.AddField(
            model_name="book",
            name="borrowed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="libraryapp.libraryuser",
            ),
        ),
    ]
