# Generated by Django 5.2.7 on 2025-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0003_remove_book_isbn_remove_libraryuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="email",
            field=models.EmailField(
                default="unknown@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
